### ISSUE TITLE
Fix: There is no lane name `run_xcov` in Fastfile

### ISSUE THREAD

**Issue by nmint8m** [nimblehq/ios-templates#293]
## Issue

Currently, the lane `run_xcov` does not exist in `Fastfile`. It was removed in PR #242.
 
## Expected

We should remove where the lane `run_xcov` is used, such as:

### In `bitrise.yml`

```yml
  test:
    steps:
    - ...
    - fastlane@3:
        inputs:
        - lane: run_xcov
```

### In `Bitrise.md`

```
## Workflows and Steps
...
| Fastlane - Run XCov | Fastlane Match | Fastlane Match | Fastlane Match |
```
